language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby-9.2.0.0
  - jruby-head

jdk:
  - oraclejdk8

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  - gem install bundler
