language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - jruby-9.0.0.0
  - jruby-head

jdk:
  - oraclejdk8
  
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
